# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\MainWindow\AirQ.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Air(object):
    def setupUi(self, Air):
        Air.setObjectName("Air")
        Air.resize(550, 420)
        self.gridLayoutWidget = QtWidgets.QWidget(Air)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 10, 531, 409))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dialAir = QtWidgets.QDial(self.gridLayoutWidget)
        self.dialAir.setMinimumSize(QtCore.QSize(0, 300))
        self.dialAir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dialAir.setMaximum(40)
        self.dialAir.setWrapping(False)
        self.dialAir.setNotchesVisible(True)
        self.dialAir.setObjectName("dialAir")
        self.gridLayout.addWidget(self.dialAir, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.minusAir = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.minusAir.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.minusAir.setFont(font)
        self.minusAir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minusAir.setObjectName("minusAir")
        self.gridLayout_3.addWidget(self.minusAir, 1, 1, 1, 1)
        self.plusAir = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.plusAir.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plusAir.setFont(font)
        self.plusAir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plusAir.setAutoFillBackground(False)
        self.plusAir.setObjectName("plusAir")
        self.gridLayout_3.addWidget(self.plusAir, 0, 1, 1, 1)
        self.valueAir = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.valueAir.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.valueAir.setFont(font)
        self.valueAir.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.valueAir.setObjectName("valueAir")
        self.gridLayout_3.addWidget(self.valueAir, 0, 0, 2, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_3)
        self.SendAir = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SendAir.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SendAir.setFont(font)
        self.SendAir.setObjectName("SendAir")
        self.horizontalLayout_11.addWidget(self.SendAir)
        self.CorrectAir = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CorrectAir.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CorrectAir.setFont(font)
        self.CorrectAir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CorrectAir.setObjectName("CorrectAir")
        self.horizontalLayout_11.addWidget(self.CorrectAir)
        self.gridLayout.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)

        self.retranslateUi(Air)
        QtCore.QMetaObject.connectSlotsByName(Air)

    def retranslateUi(self, Air):
        _translate = QtCore.QCoreApplication.translate
        Air.setWindowTitle(_translate("Air", "Расход воздуха"))
        self.minusAir.setText(_translate("Air", "-"))
        self.plusAir.setText(_translate("Air", "+"))
        self.valueAir.setInputMask(_translate("Air", "00"))
        self.valueAir.setText(_translate("Air", "00"))
        self.SendAir.setText(_translate("Air", "Отправить"))
        self.CorrectAir.setText(_translate("Air", "Скорректировать"))
