# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\MainWindow\AirQ.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Air(object):
    def setupUi(self, Air):
        Air.setObjectName("Air")
        Air.resize(452, 411)
        self.gridLayoutWidget = QtWidgets.QWidget(Air)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 10, 441, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dialAir = QtWidgets.QDial(self.gridLayoutWidget)
        self.dialAir.setMinimumSize(QtCore.QSize(0, 300))
        self.dialAir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dialAir.setMaximum(40)
        self.dialAir.setWrapping(False)
        self.dialAir.setNotchesVisible(True)
        self.dialAir.setObjectName("dialAir")
        self.gridLayout.addWidget(self.dialAir, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ValueAir = QtWidgets.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ValueAir.sizePolicy().hasHeightForWidth())
        self.ValueAir.setSizePolicy(sizePolicy)
        self.ValueAir.setMinimumSize(QtCore.QSize(50, 50))
        self.ValueAir.setSizeIncrement(QtCore.QSize(0, 0))
        self.ValueAir.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ValueAir.setFont(font)
        self.ValueAir.setObjectName("ValueAir")
        self.horizontalLayout_11.addWidget(self.ValueAir)
        self.SendAir = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SendAir.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SendAir.setFont(font)
        self.SendAir.setObjectName("SendAir")
        self.horizontalLayout_11.addWidget(self.SendAir)
        self.CorrectAir = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CorrectAir.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CorrectAir.setFont(font)
        self.CorrectAir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CorrectAir.setObjectName("CorrectAir")
        self.horizontalLayout_11.addWidget(self.CorrectAir)
        self.gridLayout.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)

        self.retranslateUi(Air)
        self.dialAir.valueChanged['int'].connect(self.ValueAir.setValue) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Air)

    def retranslateUi(self, Air):
        _translate = QtCore.QCoreApplication.translate
        Air.setWindowTitle(_translate("Air", "Form"))
        self.SendAir.setText(_translate("Air", "Отправить"))
        self.CorrectAir.setText(_translate("Air", "Скорректировать"))
        self.label_6.setText(_translate("Air", "Расход воздуха"))
