# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\MainWindow\GasQ.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gas(object):
    def setupUi(self, Gas):
        Gas.setObjectName("Gas")
        Gas.resize(452, 411)
        self.gridLayoutWidget = QtWidgets.QWidget(Gas)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 10, 441, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.dialGas = QtWidgets.QDial(self.gridLayoutWidget)
        self.dialGas.setMinimumSize(QtCore.QSize(0, 300))
        self.dialGas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dialGas.setMaximum(60)
        self.dialGas.setNotchesVisible(True)
        self.dialGas.setObjectName("dialGas")
        self.gridLayout.addWidget(self.dialGas, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ValueGas = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.ValueGas.setMinimumSize(QtCore.QSize(50, 50))
        self.ValueGas.setSizeIncrement(QtCore.QSize(0, 0))
        self.ValueGas.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ValueGas.setFont(font)
        self.ValueGas.setObjectName("ValueGas")
        self.horizontalLayout_5.addWidget(self.ValueGas)
        self.SendGas = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SendGas.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SendGas.setFont(font)
        self.SendGas.setObjectName("SendGas")
        self.horizontalLayout_5.addWidget(self.SendGas)
        self.CorrectGas = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CorrectGas.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CorrectGas.setFont(font)
        self.CorrectGas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CorrectGas.setObjectName("CorrectGas")
        self.horizontalLayout_5.addWidget(self.CorrectGas)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)

        self.retranslateUi(Gas)
        self.dialGas.valueChanged['int'].connect(self.ValueGas.setValue) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Gas)

    def retranslateUi(self, Gas):
        _translate = QtCore.QCoreApplication.translate
        Gas.setWindowTitle(_translate("Gas", "Form"))
        self.label_6.setText(_translate("Gas", "Расход газа"))
        self.SendGas.setText(_translate("Gas", "Отправить"))
        self.CorrectGas.setText(_translate("Gas", "Скорректировать"))
