# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\MainWindow\GasQ.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gas(object):
    def setupUi(self, Gas):
        Gas.setObjectName("Gas")
        Gas.resize(550, 420)
        self.gridLayoutWidget = QtWidgets.QWidget(Gas)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 10, 531, 409))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.minusGas = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.minusGas.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.minusGas.setFont(font)
        self.minusGas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minusGas.setObjectName("minusGas")
        self.gridLayout_3.addWidget(self.minusGas, 1, 1, 1, 1)
        self.plusGas = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.plusGas.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plusGas.setFont(font)
        self.plusGas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plusGas.setAutoFillBackground(False)
        self.plusGas.setObjectName("plusGas")
        self.gridLayout_3.addWidget(self.plusGas, 0, 1, 1, 1)
        self.valueGas = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.valueGas.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.valueGas.setFont(font)
        self.valueGas.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.valueGas.setObjectName("valueGas")
        self.gridLayout_3.addWidget(self.valueGas, 0, 0, 2, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.SendGas = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SendGas.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SendGas.setFont(font)
        self.SendGas.setObjectName("SendGas")
        self.horizontalLayout_5.addWidget(self.SendGas)
        self.CorrectGas = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CorrectGas.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CorrectGas.setFont(font)
        self.CorrectGas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CorrectGas.setObjectName("CorrectGas")
        self.horizontalLayout_5.addWidget(self.CorrectGas)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.dialGas = QtWidgets.QDial(self.gridLayoutWidget)
        self.dialGas.setMinimumSize(QtCore.QSize(0, 300))
        self.dialGas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dialGas.setMaximum(60)
        self.dialGas.setNotchesVisible(True)
        self.dialGas.setObjectName("dialGas")
        self.gridLayout.addWidget(self.dialGas, 0, 0, 1, 1)

        self.retranslateUi(Gas)
        QtCore.QMetaObject.connectSlotsByName(Gas)

    def retranslateUi(self, Gas):
        _translate = QtCore.QCoreApplication.translate
        Gas.setWindowTitle(_translate("Gas", "Расход газа"))
        self.minusGas.setText(_translate("Gas", "-"))
        self.plusGas.setText(_translate("Gas", "+"))
        self.valueGas.setInputMask(_translate("Gas", "00"))
        self.valueGas.setText(_translate("Gas", "00"))
        self.SendGas.setText(_translate("Gas", "Отправить"))
        self.CorrectGas.setText(_translate("Gas", "Скорректировать"))
